# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-01 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_appointment', models.DateField()),
                ('time_appointment', models.TimeField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Запись на прием к врачу',
                'verbose_name_plural': 'Записи на прием к врачам',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('work_time', models.CharField(default='09:00:00, 10:00:00, 11:00:00, 12:00:00, 13:00:00, 14:00:00, 15:00:00, 16:00:00, 17:00:00', max_length=255)),
                ('days_off', models.CharField(default='Saturday, Sunday', max_length=255)),
            ],
            options={
                'verbose_name': 'Персонал',
                'verbose_name_plural': 'Персонал',
            },
        ),
        migrations.AddField(
            model_name='patients',
            name='staff_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments_app.Staff'),
        ),
    ]
